const { request } = require('./github');

const README = `# Test summary assets

Images generated by [cedana-test-summary](https://github.com/cedana/cedana-test-summary) and embedded
in test summaries. Files are grouped by date and pruned automatically after the retention period, so
this branch only ever has one commit.
`;

// Publish a file to a branch of the repository (created when missing) and
// return its raw URL. The branch is rewritten as a single root commit on every
// publish, dropping files whose date directory is older than `retentionDays`,
// so history (and clone size) stays bounded.
async function publishAsset({ token, repository, branch, path: filePath, content, retentionDays }) {
    const base = `/repos/${repository}/git`;

    let existing = [];
    let refExists = true;
    try {
        const ref = await request(token, `${base}/ref/heads/${branch}`);
        const head = await request(token, `${base}/commits/${ref.object.sha}`);
        const tree = await request(token, `${base}/trees/${head.tree.sha}?recursive=1`);
        existing = tree.tree.filter((entry) => entry.type === 'blob');
    } catch (error) {
        if (!/failed: 404/.test(error.message)) throw error;
        refExists = false;
    }

    const cutoff = new Date(Date.now() - retentionDays * 86400000).toISOString().slice(0, 10);
    const dated = /^\d{4}-\d{2}-\d{2}\//;
    const kept = existing.filter(
        (entry) => entry.path !== filePath && entry.path !== 'README.md' && (!dated.test(entry.path) || entry.path.slice(0, 10) >= cutoff)
    );

    const blob = async (data) =>
        (await request(token, `${base}/blobs`, { method: 'POST', body: { content: data.toString('base64'), encoding: 'base64' } })).sha;
    const entries = [
        ...kept.map((entry) => ({ path: entry.path, mode: entry.mode, type: 'blob', sha: entry.sha })),
        { path: filePath, mode: '100644', type: 'blob', sha: await blob(content) },
        { path: 'README.md', mode: '100644', type: 'blob', sha: await blob(Buffer.from(README)) },
    ];
    const tree = await request(token, `${base}/trees`, { method: 'POST', body: { tree: entries } });
    const commit = await request(token, `${base}/commits`, {
        method: 'POST',
        body: { message: `Add ${filePath}`, tree: tree.sha, parents: [] },
    });

    if (refExists) {
        await request(token, `${base}/refs/heads/${branch}`, { method: 'PATCH', body: { sha: commit.sha, force: true } });
    } else {
        await request(token, `${base}/refs`, { method: 'POST', body: { ref: `refs/heads/${branch}`, sha: commit.sha } });
    }

    return `https://raw.githubusercontent.com/${repository}/${branch}/${filePath}`;
}

module.exports = { publishAsset };
